### ISSUE TITLE
unhandled exception

### ISSUE THREAD

**Issue by pattyland** [ShadowWhisperer/Remove-MS-Edge#35]
Hi,
everytime I run the script, I get the following exception on a Windows Server 2012:
```
Traceback (most recent call last):
  File "edge.py", line 91, in <module>
  File "subprocess.py", line 466, in check_output
  File "subprocess.py", line 571, in run
subprocess.CalledProcessError: Command '['powershell', '(Get-LocalUser -Name $en
v:USERNAME).SID.Value']' returned non-zero exit status 1.
[10784] Failed to execute script 'edge' due to unhandled exception!
```

**Comment by ShadowWhisperer** [comment]
Looks like the Powershell module for getting the current username, is not supported in Server 2012.
